# Generated by Django 4.2.9 on 2024-01-15 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Başında 0 olmadan giriniz...', regex='^\\d{10}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='supplier_photos/%Y/%m/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('toWho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towho', to='muhasebe.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Başında 0 olmadan giriniz...', regex='^\\d{10}$')])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='supplier_photos/%Y/%m/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fromWho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromwho', to='muhasebe.profile')),
            ],
        ),
    ]
