# Generated by Django 4.2.9 on 2024-01-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0007_remove_transaction_is_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='productImage/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='urunsahibi', to='muhasebe.profile'),
            preserve_default=False,
        ),
    ]
