# Generated by Django 4.2.9 on 2024-01-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0009_alter_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
