# Generated by Django 4.2.9 on 2024-01-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0010_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
