# Generated by Django 4.2.9 on 2024-01-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0012_customer_debt_alter_customer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=10)),
                ('payee_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muhasebe.profile')),
            ],
        ),
    ]
