# Generated by Django 4.2.9 on 2024-01-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0014_payment_customer_payment_payment_supplier_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payee_id',
        ),
    ]
