# Generated by Django 4.2.9 on 2024-01-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0015_remove_payment_payee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payee_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
