# Generated by Django 4.2.9 on 2024-01-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0018_customer_no_balance_effect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='no_balance_effect',
        ),
    ]
