# Generated by Django 4.2.9 on 2024-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0019_remove_customer_no_balance_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='no_balance_effect',
            field=models.BooleanField(default=False),
        ),
    ]
