# Generated by Django 4.2.9 on 2024-02-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0023_remove_product_price_transaction_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
    ]
