# Generated by Django 4.2.9 on 2024-02-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0026_transaction_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
