# Generated by Django 4.2.9 on 2024-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0032_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='customer_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='supplier_photos/%Y/%m/'),
        ),
    ]
