# Generated by Django 4.2.9 on 2024-05-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0033_alter_customer_photo_alter_supplier_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/2024/default.jpg', null=True, upload_to='customer_photos/%Y/%m/'),
        ),
    ]
