# Generated by Django 4.2.9 on 2024-05-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muhasebe', '0034_alter_customer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/2024/default.jpg', null=True, upload_to='profile_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/2024/default.jpg', null=True, upload_to='supplier_photos/%Y/%m/'),
        ),
    ]
